Test sidebar component
For mocking nested components, we need to define a `name` class method
on the component class. Otherwise, we get the following error:

```
NoMethodError:
 undefined method `demodulize' for nil:NilClass

 component_name = name.demodulize.underscore
```

From: https://github.com/ViewComponent/view_component/blob/5decd07842c48cbad82527daefa3fe9c65a4226a/lib/view_component/base.rb#L371